[project]
name = "fastapi-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.9.4",
    "starlette>=0.47.0",
]
